# Generated by Django 5.2.15 on 2026-07-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Family Home', 'Family Home'), ('Luxury Home', 'Luxury Home'), ('Smart Home', 'Smart Home')], max_length=30)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('garage', models.PositiveIntegerField(default=0)),
                ('area', models.PositiveIntegerField(help_text='Area in square meters')),
                ('year_built', models.PositiveIntegerField()),
                ('featured', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
