# Generated by Django 5.2.16 on 2026-07-20 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='preferred_date',
            field=models.DateField(default=datetime.date(2026, 7, 20)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
